export const GET_APPRENANTS = "GET_APPRENANTS";
export const ADD_APPRENANT = "ADD_APPRENANT";
export const UPDATE_APPRENANT = "UPDATE_APPRENANT";
export const DELETE_APPRENANT = "DELETE_APPRENANT";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT ";
export const DELETE_COMMENT = "DELETE_COMMENT ";
